# Generated by Django 2.1.7 on 2019-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_auto_20190221_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='specifitation',
            new_name='specification',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='specifitation',
            new_name='specification',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
