# Generated by Django 2.1.7 on 2019-02-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_auto_20190223_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='specification',
            field=models.TextField(blank=True),
        ),
    ]
